export { StrUtil } from './utils/str'
export { getToken, setToken, removeToken } from './utils/auth'
export { default as request, download, postAction, getAction, putAction, deleteAction, isRelogin } from './utils/request'
export { getDefaultSettings, getSettingsRuntime, installSettingsRuntime, resolveMenuLayout } from './settings'
export { default as tab } from './plugins/tab'
export { listUser, getUser, addUser, updateUser, delUser, resetUserPwd, changeUserStatus, getUserProfile, updateUserProfile, updateUserPwd, uploadAvatar, getAuthRole, updateAuthRole, deptTreeSelect } from './api/system/user'
export { listRole, getRole, addRole, updateRole, dataScope, changeRoleStatus, delRole, allocatedUserList, unallocatedUserList, authUserCancel, authUserCancelAll, authUserSelectAll, deptTreeSelect as roleDeptTreeSelect } from './api/system/role'
export { installAuthRuntime, installRequestRuntime, installTabRuntime, installUserRuntime } from './runtime'
export { defineAppModuleQiankunEntry, defineQiankunModuleEntry } from './qiankun'
export { createStandaloneApp, createStandaloneRouter } from './standalone'
export * from './types/module'
export * from './types/request'